# Character-Level LSTM in PyTorch

In this notebook, we'll construct a character-level LSTM with PyTorch. The network will train character by character on some text, then generate new text character by character. As an example, we will train on Anna Karenina. **This model will be able to generate new text based on the text from the book!**

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Below is the general architecture of the character-wise RNN.

First let's load in our required resources for data loading and model creation.

In [0]:
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F

---
## Load in Data

Then, we'll load the Anna Karenina text file and convert it into integers for our network to use.

In [0]:
# open text file and read in the data as `text`
with open("anna.txt", 'r') as f:
    text = f.read()

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

### Tokenization

In the cells, below, we're creating a couple **dictionaries** to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [4]:
# encode the text and map each character to an integer and vice versa
# we create two dictionaries
# 1. int2char, which maps integers to characters
# 2. char2int, which maps characters to unique integers

chars = tuple(set(text))
int2char = dict(enumerate(chars))
char2int = {ch: ii for ii, ch in int2char.items()}

# encode the text
encoded = np.array([char2int[ch] for ch in text])
len(encoded)

1985223

And we can see those same characters from above, encoded as integers.

In [5]:
print(chars[:5])
encoded[:100]

('M', '3', 'C', 'k', 'g')


array([ 2, 47, 21, 22, 12, 19, 37, 46, 78, 41, 41, 41, 13, 21, 22, 22, 63,
       46, 59, 21, 38, 11, 23, 11, 19, 74, 46, 21, 37, 19, 46, 21, 23, 23,
       46, 21, 23, 11,  3, 19, 42, 46, 19, 18, 19, 37, 63, 46, 20, 43, 47,
       21, 22, 22, 63, 46, 59, 21, 38, 11, 23, 63, 46, 11, 74, 46, 20, 43,
       47, 21, 22, 22, 63, 46, 11, 43, 46, 11, 12, 74, 46, 30, 77, 43, 41,
       77, 21, 63, 53, 41, 41, 39, 18, 19, 37, 63, 12, 47, 11, 43])

---
## Pre-processing the data

As you can see in our char-RNN image above, our LSTM expects an input that is **one-hot encoded** meaning that each character is converted into an integer (via our created dictionary) and *then* converted into a column vector where only it's corresponding integer index will have the value of 1 and the rest of the vector will be filled with 0's. Since we're one-hot encoding the data, let's make a function to do that!


In [0]:
def one_hot_encode(arr, n_labels):
    # initialize the encoded array
    one_hot = np.zeros((np.multiply(*arr.shape), n_labels), dtype=np.float32)

    # fill the appropriate elements with one
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1

    # finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))

    return one_hot

In [7]:
# check that the function works as expected
test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 8)
print(one_hot.shape)
print(one_hot)

(1, 3, 8)
[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]


---
## Making training mini-batches


To train on this data, we also want to create mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

In this example, we'll take the encoded characters (passed in as the `arr` parameter) and split them into multiple sequences, given by `batch_size`. Each of our sequences will be `seq_length` long.

### Creating Batches

**1. The first thing we need to do is discard some of the text so we only have completely full mini-batches.**

Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences in a batch) and $M$ is the seq_length or number of time steps in a sequence. Then, to get the total number of batches, $K$, that we can make from the array `arr`, you divide the length of `arr` by the number of characters per batch. Once you know the number of batches, you can get the total number of characters to keep from `arr`, $N * M * K$.

**2. After that, we need to split `arr` into $N$ batches.** 

You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences in a batch, so let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$.

**3. Now that we have this array, we can iterate through it to get our mini-batches.**

The idea is each batch is a $N \times M$ window on the $N \times (M * K)$ array. For each subsequent batch, the window moves over by `seq_length`. We also want to create both the input and target arrays. Remember that the targets are just the inputs shifted over by one character. The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of tokens in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `seq_length` wide.

> **TODO:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [0]:
def get_batches(arr, batch_size, seq_length):
    """
    Create a generator that returns batches of size 
    `batch_size x seq_length` from `arr`.

    Arguments:
    ==========
    :param arr: Array we want to make batches from
    :param batch_size: Batch size, number of sequences per batch
    :param seq_length: Number of encoded chars in each sequence
    """

    ### TODO: Get the number of batches we make
    n_batches = len(arr) // (batch_size * seq_length)

    ### TODO: Keep only enough characters to make full batches
    arr = arr[:(n_batches*batch_size*seq_length)]

    ### TODO: Reshape into batch_size rows
    arr = arr.reshape(batch_size, -1)

    ### TODO:iterate over the batches using a sliding window of size seq_length
    for n in range(0, arr.shape[1], seq_length):
        # the features
        x = arr[:, n:n+seq_length]
        # the targets, shifted by one
        y = np.zeros_like(x)
        try:        # takes care of the case when n+seq_length is the last element
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, n+seq_length]
        except IndexError:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, 0]
        yield x, y

---
### Test Your Implementation

Now I'll make some data sets and we can check out what's going on as we batch data. Here, as an example, I'm going to use a batch size of 8 and 50 sequence steps.

In [0]:
batches = get_batches(encoded, 8, 50)
x,y = next(batches)

In [25]:
print('x\n', x[:10, :10])
print('y\n', y[:10, :10])

x
 [[ 2 47 21 22 12 19 37 46 78 41]
 [74 30 43 46 12 47 21 12 46 21]
 [19 43 25 46 30 37 46 21 46 59]
 [74 46 12 47 19 46 14 47 11 19]
 [46 74 21 77 46 47 19 37 46 12]
 [14 20 74 74 11 30 43 46 21 43]
 [46  5 43 43 21 46 47 21 25 46]
 [24 27 23 30 43 74  3 63 53 46]]
y
 [[47 21 22 12 19 37 46 78 41 41]
 [30 43 46 12 47 21 12 46 21 12]
 [43 25 46 30 37 46 21 46 59 30]
 [46 12 47 19 46 14 47 11 19 59]
 [74 21 77 46 47 19 37 46 12 19]
 [20 74 74 11 30 43 46 21 43 25]
 [ 5 43 43 21 46 47 21 25 46 74]
 [27 23 30 43 74  3 63 53 46 65]]


---
## Defining the network with PyTorch

Below is where we'll define the network.

Next, we'll use PyTorch to define the architecture of the network. We start by defining the layers and operations we want. Then, define a method for the forward pass. We've also been given a method for predicting characters.

### Model Structure

In `__init__` the suggested structure is as follows:
* Create and store the necessary dictionaries (this has been done for you)
* Define an LSTM layer that takes as params: an input size (the number of characters), a hidden layer size `n_hidden`, a number of layers `n_layers`, a dropout probability `drop_prob`, and a batch_first boolean (True, since we are batching)
* Define a dropout layer with `dropout_prob`
* Define a fully-connected layer with params: input size `n_hidden` and output size (the number of characters)
* Finally, initialize the weights (again, this has been given)

Note that some parameters have been named and given in the `__init__` function, and we use them and store them by doing something like `self.drop_prob = drop_prob`.

---
### LSTM Inputs/Outputs

You can create a basic [LSTM layer](https://pytorch.org/docs/stable/nn.html#lstm) as follows

```python
self.lstm = nn.LSTM(input_size, n_hidden, n_layers, 
                            dropout=drop_prob, batch_first=True)
```

where `input_size` is the number of characters this cell expects to see as sequential input, and `n_hidden` is the number of units in the hidden layers in the cell. And we can add dropout by adding a dropout parameter with a specified probability; this will automatically add dropout to the inputs or outputs. Finally, in the `forward` function, we can stack up the LSTM cells into layers using `.view`. With this, we pass in a list of cells and it will send the output of one cell into the next cell.

We also need to create an initial hidden state of all zeros. This is done like so

```python
self.init_hidden()
```

In [26]:
# check if GPU is available
train_on_gpu = torch.cuda.is_available()
if(train_on_gpu):
    print('Training on GPU!')
else: 
    print('No GPU available, training on CPU; consider making n_epochs very small.')

Training on GPU!


In [27]:
torch.cuda.get_device_name()

'Tesla P100-PCIE-16GB'

In [0]:
class CharRNN(nn.Module):
    
    def __init__(self, tokens, n_hidden=256, n_layers=2,
                               drop_prob=0.5, lr=0.001):
        super().__init__()
        self.n_hidden = n_hidden
        self.n_layers = n_layers
        self.drop_prob = drop_prob
        self.lr = lr
        
        # creating character dictionaries
        self.chars = tokens
        self.int2char = dict(enumerate(self.chars))
        self.char2int = {ch: ii for ii, ch in self.int2char.items()}
        
        ## TODO: define the layers of the model
        self.lstm = nn.LSTM(len(tokens), n_hidden, n_layers, dropout=drop_prob, 
                            batch_first=True)
        self.dropout = nn.Dropout(drop_prob)
        self.fc = nn.Linear(n_hidden, len(tokens))

    def forward(self, x, hidden):
        ''' Forward pass through the network. 
            These inputs are x, and the hidden/cell state `hidden`. '''
                
        ## TODO: Get the outputs and the new hidden state from the lstm
        out, hidden = self.lstm(x, hidden)
        out = self.dropout(out)
        out = out.contiguous().view(-1, n_hidden)
#         print(out.shape)
        out = self.fc(out)
        # return the final output and the hidden state
        return out, hidden
    
    
    def init_hidden(self, batch_size):
    #     ''' Initializes hidden state '''
    #     # Create two new tensors with sizes n_layers x batch_size x n_hidden,
    #     # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        dummy = weight.new_zeros(self.n_layers, batch_size, self.n_hidden)
        if (train_on_gpu):
            hidden = (weight.new_zeros(self.n_layers, batch_size, self.n_hidden).cuda(),
                  weight.new_zeros(self.n_layers, batch_size, self.n_hidden).cuda())
        else:
            hidden = (weight.new_zeros(self.n_layers, batch_size, self.n_hidden),
                      weight.new_zeros(self.n_layers, batch_size, self.n_hidden))
        # if train_on_gpu:
        #     hidden = (nn.init.kaiming_normal_(dummy).cuda(),
        #               nn.init.kaiming_normal_(dummy).cuda())
        # else:
        #     hidden = (nn.init.kaiming_normal_(dummy),
        #               nn.init.kaiming_normal_(dummy))
        # print(np.shape(hidden[0]))
        return hidden

In [0]:
def train(net, data, epochs=10, batch_size=10, seq_length=50, lr=0.001, clip=5, val_frac=0.1, print_every=10):
    ''' Training a network 
    
        Arguments
        ---------
        
        net: CharRNN network
        data: text data to train the network
        epochs: Number of epochs to train
        batch_size: Number of mini-sequences per mini-batch, aka batch size
        seq_length: Number of character steps per mini-batch
        lr: learning rate
        clip: gradient clipping
        val_frac: Fraction of data to hold out for validation
        print_every: Number of steps for printing training and validation loss
    
    '''
    net.train()
    
    opt = torch.optim.Adam(net.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    
    # create training and validation data
    val_idx = int(len(data)*(1-val_frac))
    data, val_data = data[:val_idx], data[val_idx:]
    
    if(train_on_gpu):
        net.cuda()
    
    counter = 0
    n_chars = len(net.chars)
    for e in range(epochs):
        # initialize hidden state
        h = net.init_hidden(batch_size)
        
        for x, y in get_batches(data, batch_size, seq_length):
            counter += 1
            
            # One-hot encode our data and make them Torch tensors
            x = one_hot_encode(x, n_chars)
            inputs, targets = torch.from_numpy(x), torch.from_numpy(y)
            # print(inputs.shape)
            if(train_on_gpu):
                inputs, targets = inputs.cuda(), targets.cuda()

            # Creating new variables for the hidden state, otherwise
            # we'd backprop through the entire training history
            h = tuple([each.data for each in h])

            # zero accumulated gradients
            net.zero_grad()
            
            # get the output from the model
            output, h = net(inputs, h)
            
            # calculate the loss and perform backprop
            loss = criterion(output, targets.contiguous().view(batch_size*seq_length).long())
            loss.backward()
            # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
            nn.utils.clip_grad_norm_(net.parameters(), clip)
            opt.step()
            
            # loss stats
            if counter % print_every == 0:
                # Get validation loss
                val_h = net.init_hidden(batch_size)
                val_losses = []
                net.eval()
                for x, y in get_batches(val_data, batch_size, seq_length):
                    # One-hot encode our data and make them Torch tensors
                    x = one_hot_encode(x, n_chars)
                    x, y = torch.from_numpy(x), torch.from_numpy(y)
                    
                    # Creating new variables for the hidden state, otherwise
                    # we'd backprop through the entire training history
                    val_h = tuple([each.data for each in val_h])
                    
                    inputs, targets = x, y
                    if(train_on_gpu):
                        inputs, targets = inputs.cuda(), targets.cuda()

                    output, val_h = net(inputs, val_h)
                    val_loss = criterion(output, targets.contiguous().view(batch_size*seq_length).long())
                
                    val_losses.append(val_loss.item())
                
                net.train() # reset to train mode after iterationg through validation data
                
                print("Epoch: {}/{}...".format(e+1, epochs),
                      "Step: {}...".format(counter),
                      "Loss: {:.4f}...".format(loss.item()),
                      "Val Loss: {:.4f}".format(np.mean(val_losses)))

In [34]:
## TODO: set you model hyperparameters
# define and print the net
n_hidden=256
n_layers=2

rnn = CharRNN(chars, n_hidden, n_layers)
print(rnn)

CharRNN(
  (lstm): LSTM(83, 256, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc): Linear(in_features=256, out_features=83, bias=True)
)


In [35]:
batch_size = 128
seq_length = 100
n_epochs =  50     # start small if you are just testing initial behavior

# train the model
train(rnn, encoded, epochs=n_epochs, batch_size=batch_size, seq_length=seq_length, 
      lr=0.001, print_every=50)

Epoch: 1/50... Step: 50... Loss: 3.1654... Val Loss: 3.1199
Epoch: 1/50... Step: 100... Loss: 3.1301... Val Loss: 3.1125
Epoch: 2/50... Step: 150... Loss: 3.0535... Val Loss: 3.0228
Epoch: 2/50... Step: 200... Loss: 2.8151... Val Loss: 2.7421
Epoch: 2/50... Step: 250... Loss: 2.5675... Val Loss: 2.5269
Epoch: 3/50... Step: 300... Loss: 2.5006... Val Loss: 2.4263
Epoch: 3/50... Step: 350... Loss: 2.4429... Val Loss: 2.3647
Epoch: 3/50... Step: 400... Loss: 2.3570... Val Loss: 2.3123
Epoch: 4/50... Step: 450... Loss: 2.2904... Val Loss: 2.2663
Epoch: 4/50... Step: 500... Loss: 2.2914... Val Loss: 2.2219
Epoch: 4/50... Step: 550... Loss: 2.2434... Val Loss: 2.1857
Epoch: 5/50... Step: 600... Loss: 2.1600... Val Loss: 2.1404
Epoch: 5/50... Step: 650... Loss: 2.1502... Val Loss: 2.1047
Epoch: 6/50... Step: 700... Loss: 2.1089... Val Loss: 2.0705
Epoch: 6/50... Step: 750... Loss: 2.0604... Val Loss: 2.0390
Epoch: 6/50... Step: 800... Loss: 2.0508... Val Loss: 2.0087
Epoch: 7/50... Step: 850.

## Getting the best model

To set your hyperparameters to get the best performance, you'll want to watch the training and validation losses. If your training loss is much lower than the validation loss, you're overfitting. Increase regularization (more dropout) or use a smaller network. If the training and validation losses are close, you're underfitting so you can increase the size of the network.

## Hyperparameters

Here are the hyperparameters for the network.

In defining the model:
* `n_hidden` - The number of units in the hidden layers.
* `n_layers` - Number of hidden LSTM layers to use.

We assume that dropout probability and learning rate will be kept at the default, in this example.

And in training:
* `batch_size` - Number of sequences running through the network in one pass.
* `seq_length` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lr` - Learning rate for training

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `n_hidden` and `n_layers`. I would advise that you always use `n_layers` of either 2/3. The `n_hidden` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `n_hidden` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

## Checkpoint

After training, we'll save the model so we can load it again later if we need too. Here I'm saving the parameters needed to create the same architecture, the hidden layer hyperparameters and the text characters.

In [0]:
# change the name, for saving multiple files
model_name = 'rnn_x_epoch.net'

checkpoint = {'n_hidden': rnn.n_hidden,
              'n_layers': rnn.n_layers,
              'state_dict': rnn.state_dict(),
              'tokens': rnn.chars}

with open(model_name, 'wb') as f:
    torch.save(checkpoint, f)

---
## Making Predictions

Now that the model is trained, we'll want to sample from it and make predictions about next characters! To sample, we pass in a character and have the network predict the next character. Then we take that character, pass it back in, and get another predicted character. Just keep doing this and you'll generate a bunch of text!

### A note on the `predict`  function

The output of our RNN is from a fully-connected layer and it outputs a **distribution of next-character scores**.

> To actually get the next character, we apply a softmax function, which gives us a *probability* distribution that we can then sample to predict the next character.

### Top K sampling

Our predictions come from a categorical probability distribution over all the possible characters. We can make the sample text and make it more reasonable to handle (with less variables) by only considering some $K$ most probable characters. This will prevent the network from giving us completely absurd characters while allowing it to introduce some noise and randomness into the sampled text. Read more about [topk, here](https://pytorch.org/docs/stable/torch.html#torch.topk).

In [0]:
def predict(net, char, h=None, top_k=None):
        ''' Given a character, predict the next character.
            Returns the predicted character and the hidden state.
        '''
        
        # tensor inputs
        x = np.array([[net.char2int[char]]])
        x = one_hot_encode(x, len(net.chars))
        inputs = torch.from_numpy(x)
        
        if(train_on_gpu):
            inputs = inputs.cuda()
        
        # detach hidden state from history
        h = tuple([each.data for each in h])
        # get the output of the model
        out, h = net(inputs, h)

        # get the character probabilities
        p = F.softmax(out, dim=1).data
        if(train_on_gpu):
            p = p.cpu() # move to cpu
        
        # get top characters
        if top_k is None:
            top_ch = np.arange(len(net.chars))
        else:
            p, top_ch = p.topk(top_k)
            top_ch = top_ch.numpy().squeeze()
        
        # select the likely next character with some element of randomness
        p = p.numpy().squeeze()
        char = np.random.choice(top_ch, p=p/p.sum())
        
        # return the encoded value of the predicted char and the hidden state
        return net.int2char[char], h

### Priming and generating text 

Typically you'll want to prime the network so you can build up a hidden state. Otherwise the network will start out generating characters at random. In general the first bunch of characters will be a little rough since it hasn't built up a long history of characters to predict from.

In [0]:
def sample(net, size, prime='The', top_k=None):
        
    if(train_on_gpu):
        net.cuda()
    else:
        net.cpu()
    
    net.eval() # eval mode
    
    # First off, run through the prime characters
    chars = [ch for ch in prime]
    h = net.init_hidden(1)
    for ch in prime:
        char, h = predict(net, ch, h, top_k=top_k)

    chars.append(char)
    
    # Now pass in the previous character and get a new one
    for ii in range(size):
        char, h = predict(net, chars[-1], h, top_k=top_k)
        chars.append(char)

    return ''.join(chars)

In [39]:
print(sample(rnn, 1000, prime="Anna", top_k=5))

Anna Alexandrovitch, so was at the conversation
alone, to her that there were said that the chief sense there was a love to him. Anna would
not see the
docker who wished her, had answered to hurrout. And the
peasants she saw there sides and standing
to the country.
He would have all all out of the friends, thinking of
the contrart and
work of her husband.

"When it was so the considered time will tigh, this sensite the straight of the carriage and a samilise with his fruends, I have no marshal
would she work.
Why's anyone she doesn't believe," he said, and his strong
of the persousen time was being heart. Alexey Alexandrovitch she consequently as she
with her head, when he saw that the teate at his blush. A clearly with a tried. He
heard the mushroom, and as it was a speal of a mones of this strengs, was still holding them with her and another, and she could not have asked hearily as he had been
bather in haste and sat fact at homon. The sight
of the mirth the sincere wished in her and

## Loading a checkpoint

In [40]:
# Here we have loaded in a model that trained over 20 epochs `rnn_20_epoch.net`
with open('rnn_x_epoch.net', 'rb') as f:
    checkpoint = torch.load(f)
    
loaded = CharRNN(checkpoint['tokens'], n_hidden=checkpoint['n_hidden'], n_layers=checkpoint['n_layers'])
loaded.load_state_dict(checkpoint['state_dict'])

<All keys matched successfully>

In [41]:
# Sample using a loaded model
print(sample(loaded, 2000, top_k=5, prime="And Levin said"))

And Levin said
that he said, and
with the point. And who did not
to that
would have to see to see to a simple, and, taking the colan tone the sort
that to be some weak at health was
their husband, well she did not say. He was sating to the same, he was as assuping all the meeting so might, they always still, and was
the porter.

"Why dinn't be a learned," she said on his beausy that so as some other white shoulders of her hand with a smile with his brights of a still sening and hands of angiligette, the chear of sort of
alraid, she
had asked the paind of his brother of the completel thoughts he would have stoll when they her face, the soliture.

Thrithing at the princess and all thought of his
head, as he
day to shake
her house and sat
she wished to the cares,
he had at his feet that he would bring the mire of her heart,
a prince. "Yes, I see that the same," he went up here of his brother to his
head at our table, and to tell you he did not consider him by home. At the cold they had be